services:
  postgres:
    image: postgres:latest
    container_name: tastyroad_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: tastyroad_api
    restart: always
    ports:
      - 8800:8800
    env_file:
      - .env
    volumes:
      - ./api/src:/usr/src/app
    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tastyroad_frontend
    restart: always
    ports:
      - "3300:3300"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true


volumes:
  postgres_data: