# Generated by Django 6.0.2 on 2026-03-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
                ("zone", models.CharField(max_length=100)),
                ("distance", models.FloatField(help_text="Distance in km")),
                ("duration", models.FloatField(help_text="Duration in hours")),
                ("difficulty", models.CharField(max_length=50)),
                ("diet", models.CharField(max_length=50)),
                ("speciality", models.CharField(max_length=200)),
                ("facts", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Itineraries",
            },
        ),
    ]
