# Generated by Django 6.0.2 on 2026-03-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0001_initial"),
        ("places", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                ("id_step", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("picture", models.URLField(blank=True)),
                ("step_order", models.PositiveIntegerField()),
                (
                    "food_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="steps",
                        to="places.foodplace",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="itineraries.itinerary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step",
                "verbose_name_plural": "Steps",
                "ordering": ["step_order"],
            },
        ),
    ]
