# Generated by Django 6.0.2 on 2026-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0002_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
