# Generated by Django 6.0.2 on 2026-03-09 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0005_comment_delete_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="picture",
            field=models.URLField(blank=True),
        ),
    ]
