# Generated by Django 6.0.2 on 2026-03-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0006_alter_comment_review_alter_step_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
