# Generated by Django 6.0.2 on 2026-03-09 16:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0007_alter_step_description_alter_step_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_itineraries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itineraries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="distance",
            field=models.DecimalField(
                decimal_places=2, help_text="Distance en km", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="duration",
            field=models.DecimalField(
                decimal_places=2, help_text="Durée en heures", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="speciality",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="zone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="step",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="step",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="step",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
