# Generated by Django 6.0.2 on 2026-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0008_itinerary_favorites_itinerary_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="step",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
