# Generated by Django 6.0.2 on 2026-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0009_alter_step_latitude_alter_step_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="distance",
            field=models.FloatField(help_text="Distance en km"),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="duration",
            field=models.FloatField(help_text="Durée en heures"),
        ),
    ]
