# Generated by Django 6.0.2 on 2026-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0010_alter_itinerary_distance_alter_itinerary_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itinerary",
            options={
                "ordering": ["id_itinerary"],
                "verbose_name_plural": "Itineraries",
            },
        ),
        migrations.RenameField(
            model_name="itinerary",
            old_name="id",
            new_name="id_itinerary",
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="id_itinerary",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
