# Generated by Django 6.0.2 on 2026-03-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodPlace",
            fields=[
                ("id_foodplace", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("description", models.TextField(blank=True)),
                ("mapbox_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
