# Generated by Django 6.0.2 on 2026-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_alter_foodplace_mapbox_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodplace",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
