# Generated by Django 6.0.2 on 2026-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_foodplace_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodplace",
            options={"ordering": ["id_foodplace"]},
        ),
    ]
