# Generated by Django 6.0.2 on 2026-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_alter_foodplace_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodplace",
            name="mapbox_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="foodplace",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
