name: 🚀 CD Deploy to Production

on:
  push:
    branches: [main] # Runs only when code is merged/pushed to main

jobs:
  # 🐳 Build & Push Docker Images
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: backend
            context: ./api
            dockerfile: ./api/Dockerfile
            image_name: tastyroad-backend
            target: ""
          - service: frontend
            context: ./client
            dockerfile: ./client/Dockerfile
            image_name: tastyroad-frontend
            target: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # # 🚀 Trigger Render Deployment
  # deploy-render:
  #   name: Trigger Render
  #   runs-on: ubuntu-latest
  #   needs: build-and-push 
  #   steps:
  #     - name: Deploy Backend
  #       run: curl -X GET ${{ secrets.RENDER_WEBHOOK_MUSIQUE }}
