name: 🚀 CD Deploy to Production

on:
  push:
    branches: [main]

jobs:
  ci-checks:
    uses: ./.github/workflows/ci-checks.yml

  deploy-render:
    name: Trigger Render
    needs: [ci-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to Render
        run: |
          echo "Appel du Deploy Hook Render..."
          curl -X POST -f "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
